import { Product } from '../types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Product 1',
    description: 'Description for product 1',
    price: 100,
    originalPrice: 120,
    category: 'dress',
    images: ['/images/product1_1.jpg', '/images/product1_2.jpg'],
    sizes: ['S', 'M', 'L'],
    colors: ['red', 'blue'],
    stock: 10,
    status: 'available',
    rating: 4.5,
    reviewCount: 150,
    isNew: true,
    isSale: false,
    tags: ['popular', 'summer collection'],
    createdAt: '2023-01-01T00:00:00.000Z',
    updatedAt: '2023-01-01T00:00:00.000Z',
  },
  {
    id: '2',
    name: 'Product 2',
    description: 'Description for product 2',
    price: 200,
    category: 'shoes',
    images: ['/images/product2_1.jpg'],
    sizes: ['S', 'M', 'XL'],
    colors: ['black'],
    stock: 5,
    status: 'available',
    rating: 4.0,
    reviewCount: 75,
    isNew: false,
    isSale: true,
    tags: ['sale', 'limited stock'],
    createdAt: '2023-01-02T00:00:00.000Z',
    updatedAt: '2023-01-02T00:00:00.000Z',
  },
  {
    id: '3',
    name: 'Product 3 - Premium Shirt',
    description: 'A high-quality premium shirt, perfect for formal occasions.',
    price: 75,
    originalPrice: 90,
    category: 'top',
    images: [
      '/images/product3_1.jpg',
      '/images/product3_2.jpg',
      '/images/product3_3.jpg',
    ],
    sizes: ['M', 'L', 'XL'],
    colors: ['white', 'blue'],
    stock: 25,
    status: 'available',
    rating: 4.8,
    reviewCount: 210,
    isNew: true,
    isSale: false,
    tags: ['new arrival', 'formal wear', 'cotton'],
    createdAt: '2023-03-15T00:00:00.000Z',
    updatedAt: '2023-03-15T00:00:00.000Z',
  },
];
